services:
  - type: web
    name: shiksha-setu-backend
    env: python
    plan: free
    branch: feature-branch-name
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
